apiVersion: v1
kind: Service
metadata:
  name: pomelo-connector
  labels:
    app: pomelo-connector
  namespace: pomelo
spec:
  ports:
  - port: 3010
    name: connector
  clusterIP: None
  selector:
    app: pomelo-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomelo-connector
  labels:
    app: pomelo-connector
  namespace: pomelo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomelo-connector
  template:
    metadata:
      labels:
        app: pomelo-connector
    spec:
      containers:
      - name: pomelo-connector
        image: maxc0d3r/pomelo-k8s:v2
        imagePullPolicy: Never
        ports:
          - containerPort: 3010
            name: connector
        env:
          - name: REDIS_HOST
            value: redis.default
          - name: REDIS_PORT
            value: "6379"
          - name: SERVICE_DOMAIN
            value: maxc0d3r.test
